/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.example.todo.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the TodoItem service. Represents a row in the &quot;Todo_TodoItem&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.example.todo.model.impl.TodoItemModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.example.todo.model.impl.TodoItemImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see TodoItem
 * @generated
 */
@ProviderType
public interface TodoItemModel
	extends BaseModel<TodoItem>, GroupedModel, ShardedModel,
			StagedAuditedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a todo item model instance should use the {@link TodoItem} interface instead.
	 */

	/**
	 * Returns the primary key of this todo item.
	 *
	 * @return the primary key of this todo item
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this todo item.
	 *
	 * @param primaryKey the primary key of this todo item
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this todo item.
	 *
	 * @return the uuid of this todo item
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this todo item.
	 *
	 * @param uuid the uuid of this todo item
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the todo item ID of this todo item.
	 *
	 * @return the todo item ID of this todo item
	 */
	public long getTodoItemId();

	/**
	 * Sets the todo item ID of this todo item.
	 *
	 * @param todoItemId the todo item ID of this todo item
	 */
	public void setTodoItemId(long todoItemId);

	/**
	 * Returns the group ID of this todo item.
	 *
	 * @return the group ID of this todo item
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this todo item.
	 *
	 * @param groupId the group ID of this todo item
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this todo item.
	 *
	 * @return the company ID of this todo item
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this todo item.
	 *
	 * @param companyId the company ID of this todo item
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this todo item.
	 *
	 * @return the user ID of this todo item
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this todo item.
	 *
	 * @param userId the user ID of this todo item
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this todo item.
	 *
	 * @return the user uuid of this todo item
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this todo item.
	 *
	 * @param userUuid the user uuid of this todo item
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this todo item.
	 *
	 * @return the user name of this todo item
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this todo item.
	 *
	 * @param userName the user name of this todo item
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this todo item.
	 *
	 * @return the create date of this todo item
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this todo item.
	 *
	 * @param createDate the create date of this todo item
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this todo item.
	 *
	 * @return the modified date of this todo item
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this todo item.
	 *
	 * @param modifiedDate the modified date of this todo item
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the title of this todo item.
	 *
	 * @return the title of this todo item
	 */
	@AutoEscape
	public String getTitle();

	/**
	 * Sets the title of this todo item.
	 *
	 * @param title the title of this todo item
	 */
	public void setTitle(String title);

	/**
	 * Returns the description of this todo item.
	 *
	 * @return the description of this todo item
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this todo item.
	 *
	 * @param description the description of this todo item
	 */
	public void setDescription(String description);

	/**
	 * Returns the due date of this todo item.
	 *
	 * @return the due date of this todo item
	 */
	public Date getDueDate();

	/**
	 * Sets the due date of this todo item.
	 *
	 * @param dueDate the due date of this todo item
	 */
	public void setDueDate(Date dueDate);

	/**
	 * Returns the completed of this todo item.
	 *
	 * @return the completed of this todo item
	 */
	public boolean getCompleted();

	/**
	 * Returns <code>true</code> if this todo item is completed.
	 *
	 * @return <code>true</code> if this todo item is completed; <code>false</code> otherwise
	 */
	public boolean isCompleted();

	/**
	 * Sets whether this todo item is completed.
	 *
	 * @param completed the completed of this todo item
	 */
	public void setCompleted(boolean completed);

	/**
	 * Returns the priority of this todo item.
	 *
	 * @return the priority of this todo item
	 */
	public int getPriority();

	/**
	 * Sets the priority of this todo item.
	 *
	 * @param priority the priority of this todo item
	 */
	public void setPriority(int priority);

	@Override
	public TodoItem cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}